Server/MetaStudio/NFTs/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,SelectField,validators

class CreateNFT(FlaskForm):
    nft_name=StringField("Enter the Subject Name",validators=[validators.required()])
    submit=SubmitField("Add Subject")
    

Server/MetaStudio/NFTs/views.py
from collections import deque
from MetaStudio import app,db,account,MetaStudioNFT,Contract
from MetaStudio.Models import UserProfile,Collection
import os
import sys
from pathlib import Path
import requests
from datetime import datetime,date
from flask import Blueprint,render_template,redirect,url_for,request
from flask_login import login_required, current_user,logout_user,login_user
import json
OPENSEA_URL = "https://testnets.opensea.io/assets/avalanche-fuji/{}/{}"

profile_blueprint=Blueprint("Profile",__name__,template_folder="templates",static_folder="static")
def upload_to_ipfs_pinata(image_binary,filename):
    PINATA_BASE_URL = "https://api.nft.storage/"
    endpoint = "upload"
    headers = {
    'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweGQ3Mjk5NDcyNDVlNTlhZjNlYTM2MTg3M2ZCMWUxYTdCRGI1MjUzMUEiLCJpc3MiOiJuZnQtc3RvcmFnZSIsImlhdCI6MTY4OTY3NzAzMjY5NSwibmFtZSI6Ik1ldGFTZXVtIn0.U7iPXi9isqLCU4zZeg3PDYRtBOL3JNS6hTMFPSPwPbU',
    'accept': 'application/json',
    'Content-Type': 'image/*'
    }
    # with Path(path).open("rb") as fp:
    #     image_binary = fp.read()
    response = requests.post(
        PINATA_BASE_URL + endpoint,
        data=image_binary,
        headers=headers,
    )
    uri="https://ipfs.io/ipfs/{}?filename={}".format(response.json()['value']["cid"], filename)
    return uri
@profile_blueprint.route("/Authenticate", methods=["GET","POST"])
def Authenticate():
    if request.method=="POST":
        username = request.form.get('username')
        password = request.form.get('password')
        user=UserProfile.query.filter_by(user_email=username,user_password=password).first()
        if user!=None:
            login_user(user, remember=True)
            return redirect(url_for("Profile.Dashboard"))
        else:
            return redirect(url_for("home"))

@profile_blueprint.route("/CreateUser", methods=["GET","POST"])
def CreateUser():
    if request.method=="POST":
        username = request.form.get('username')
        useremail = request.form.get('useremail')
        useraddress = request.form.get('useraddress')
        password = request.form.get('password')
        user=UserProfile(useraddress,username,useremail,password)
        db.session.add(user)
        db.session.commit()
        if user!=None:
            login_user(user, remember=True)
            return redirect(url_for("Profile.Dashboard"))
        else:
            return redirect(url_for("home"))
@profile_blueprint.route("/CreateCollection", methods=["GET","POST"])
def CreateCollection():
    if request.method=="POST":
        UserAddress = request.form.get('UserAddress')
        user=UserProfile.query.filter_by(user_address=UserAddress).first()
        if user!=None:
            collectionToken = request.form.get('collectionToken')
            collectionname = request.form.get('collectionname')
            simple_collection=MetaStudioNFT.deploy(collectionname,collectionToken,{"from": account})
            coll=Collection(collectionname,collectionToken,"",simple_collection.address)
            db.session.add(coll)
            user.Collections.append(coll)
            db.session.commit()
            return {"code":200, "Collection Address":OPENSEA_URL.format(simple_collection.address,"")}
        return {"code":404,"Message":"No Data Found"}
@profile_blueprint.route("/CreateNFT", methods=["GET","POST"])
def CreateNFT():
    if request.method=="POST":
        collectionname = request.form.get('collectionname')
        collection=Collection.query.filter_by(collection_name=collectionname).first()
        if collection!=None:
            nftName = request.form.get('nftName')
            nftDescription = request.form.get('nftDescription')
            user_address = request.form.get('useraddress')
            nftFile = request.files["nftFile"]
            medial_url=upload_to_ipfs_pinata(nftFile.read(),nftFile.filename)
            metadata={
            "image": medial_url,
            "name": nftName,
            "description": nftDescription,
            "external_link": None,
            "animation_url": None,
            "traits": []
            }
            metadata_json=json.dumps(metadata).encode()
            meta_data_uri=upload_to_ipfs_pinata(metadata_json,nftName+".json")
            collectioncontract=Contract(collection.contract_address)
            tx=collectioncontract.safeMint(user_address,meta_data_uri, {"from": account})
            tx.wait(1)
            return {"code":200, "Minted NFT": OPENSEA_URL.format(collectioncontract.address,collectioncontract.tokenCounter()-1)}
        # tx = simple_collectible.safeMint(current_user.user_address,meta_data_uri, {"from": account})
        # tx.wait(1)
        return {"code":404,"Message":"No Data Found"}       
    
def load_user_nfts(collections):
    NFTs=[]
    for collection in collections:
        MetaCanvasNFT = Contract(collection.contract_address)
        count=MetaCanvasNFT.retrieve()
        for i in range(0,count):
            uri=MetaCanvasNFT.retrieve_uri(i)
            response = requests.request("GET", uri)
            nfts_owned=json.loads(response.text)
            nfts_owned["contract_address"]=collection.contract_address
            nfts_owned["token_uri"]=i
            NFTs.append(nfts_owned)
    return NFTs

@profile_blueprint.route("/Dashboard/")
@login_required
def Dashboard():
    myCollections=current_user.Collections
    NFTs=load_user_nfts(myCollections)
    print(NFTs)
    return render_template("dashboard.html",NFTs=NFTs)



@profile_blueprint.route("/Logout", methods=["GET","POST"])
@login_required
def Logout():
    logout_user()
    return redirect(url_for("home"))


@profile_blueprint.route("/AuthenticateVR", methods=["GET","POST"])
def AuthenticateVR():
    if request.method=="POST":
        username = request.form.get('username')
        password = request.form.get('password')
        user=UserProfile.query.filter_by(user_email=username,user_password=password).first()
        if user!=None:
            return {"code":200,"Id":user.id,"User Name":user.user_name,"User Address":user.user_address,"User Email":user.user_email}
    return {"code":404,"Message":"No Data Found"}

Server/MetaStudio/__init__.py
from brownie import *
from os.path import join

import os,sys
from flask import Flask,render_template, redirect,url_for
from flask_sqlalchemy import SQLAlchemy
from flask_restful import Api
from flask_login import LoginManager,UserMixin

direc=os.path.abspath(os.path.dirname(__file__))
app=Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"]="sqlite:///"+os.path.join(direc,"data.sqlite")
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"]=False
SECRET_KEY = os.urandom(32)
app.config['SECRET_KEY'] = SECRET_KEY
db=SQLAlchemy(app)
api=Api(app=app)
app.app_context().push()
project_path="./MetaStudio/static/BrownieProject"
p = project.load(project_path, name="MetaStudioNFT")
p.load_config()
from brownie import network,Contract
network.connect('fuji')
sample_token_uri = "https://ipfs.io/ipfs/Qmd9MCGtdVz2miNumBHDbvj8bigSgTwnr4SbyH6DNnpWdt?filename=0-PUG.json"
OPENSEA_URL = "https://testnets.opensea.io/assets/goerli/{}/{}"

from brownie.project.MetaStudioNFT import MetaStudioNFT
account = accounts.add("8ad2efe017767f747b402df39b0146c3d99ce2910b5708d7bff12084f8f00185")

from MetaStudio.NFTs.views import profile_blueprint

app.register_blueprint(profile_blueprint,url_prefix="/Profile/")


from MetaStudio.REST.RESTful import MyCollection

api.add_resource(MyCollection, "/rest/mycollection/<string:address>/")

Server/MetaStudio/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!-- <script src="{{url_for('static',filename='js/metamask-sdk.js')}}"></script> -->
    <title>MetaStudio</title>
    <style>
        body {
            background-color: rgb(25, 25, 27);
            color: white;
            padding-left: 15px;
            padding-right: 15px;
        }

        .nav-item {
            color: white;
        }

        .modal-body {
            background-color: rgb(25, 25, 27);
            ;
        }

        .modal-content {
            background-color: rgb(25, 25, 27);
            ;

        }

        .modal-footer {
            background-color: rgb(25, 25, 27);
            ;

        }

        .modal-header {
            background-color: rgb(25, 25, 27);
            ;

        }

        .nav-item:hover {
            color: white;
        }

        .form-img {
            background-repeat: no-repeat;
            background-image: url("#");
            /* Background Image for Forms*/
            background-blend-mode: lighten;
            background-attachment: fixed;
            /* border:1px solid; */
            background-size: 100% 100%;
        }

        .page-header {
            color: white;
            font-family: Georgia, 'Times New Roman', Times, serif;
            text-align: center;
            padding: 0%;
            border-bottom: 1px solid yellow;
            letter-spacing: 5px;
        }

        p.subhead {
            color: white;
            margin: 0%;
            text-align: center;
            font-variant: small-caps;
        }

        .main-content {
            padding: 15px;
            padding-top: 25px;
        }

        .navbar {
            background-color: black !important;
        }

        .form-img {
            background-repeat: no-repeat;
            background-image: url("#");
            /* Background Image for Forms*/
            background-blend-mode: lighten;
            background-attachment: fixed;
            /* border:1px solid; */
            background-size: 100% 100%;
        }

        .card {
            background-color: inherit !important;
        }

        .form-style {
            margin: 0 auto;
            width: 60%;
        }

        .form-control {
            margin-top: 10px;
            margin-bottom: 10px;
        }

        table.table-fit {
            width: auto !important;
            table-layout: auto !important;
        }

        .timeline {
            white-space: nowrap;
            overflow-x: auto;
            padding: 30px 0 10px 0;
            position: relative;
        }

        .entry {
            display: inline-block;
            vertical-align: top;
            background: inherit;
            color: white;
            padding: 10px;
            font-size: 12px;
            text-align: center;
            position: relative;
            border: 1px solid white;
            border-top: 4px solid white;
            border-radius: 3px;
            min-width: 200px;
            min-height: 200px;
            max-width: 500px;
        }

        .entry img {
            display: block;
            max-width: 100%;
            height: auto;
            margin-bottom: 10px;
        }

        .entry:after {
            content: '';
            display: block;
            background: white;
            width: 7px;
            height: 7px;
            border-radius: 6px;
            border: 3px solid white;
            position: absolute;
            left: 50%;
            top: -30px;
            margin-left: -6px;
        }

        .entry:before {
            content: '';
            display: block;
            background: white;
            width: 5px;
            height: 20px;
            position: absolute;
            left: 50%;
            top: -20px;
            margin-left: -2px;
        }

        .entry h1 {
            color: rgb(241, 238, 28);
            font-size: 18px;
            font-family: Georgia, serif;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .entry h2 {
            letter-spacing: .2em;
            margin-bottom: 10px;
            font-size: 14px;
        }

        .bar {
            height: 4px;
            background: white;
            width: auto;
            position: relative;
            top: 13px;
            left: 0;
        }
    </style>
</head>

<body>
    <div class="row sticky-top" style="background-color: black;">
        <div class="col-md-5">
            <h4 class="page-header">MetaStudio</h4>
            <p class="subhead"> Metaverse Platform for Artists to Create AI ART</p>
        </div>
        <div class="col-md-7">
            <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('Profile.Dashboard')}}">Dashboard</a>
                    </li>
                    {% if current_user.is_authenticated==True %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">Welcome, {{current_user.user_name}}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('Profile.Logout')}}">Logout </a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>

    <div class="row main-content">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

Server/MetaStudio/templates/homepage.html
{% extends "base.html" %}

{% block content %}
<div class="container card" style="color: white!important;">

    <br>
    <br>
    <h3 class="title" style="text-align: center;">Login</h3>
    <div class="col-md-12 form-img card-body ">
        <form method="POST" action="{{url_for('Profile.Authenticate')}}" style="width: 50%;margin-left : 25%;">
            <div class="row">
                <div class="col">
                    <input class="form-control input-lg" type="text" name="username" placeholder="UserName"
                        autofocus="">
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <input class="form-control input-lg" type="password" name="password" placeholder="Password">
                </div>
            </div>
            <center><button class="btn btn-success font-weight-bold" type="submit">Login</button></center>
        </form>
    </div>
    <br>
    <br>
    <h3 class="title" style="text-align: center;">Register Account</h3>
    <div class="col-md-12 form-img card-body ">
        <form method="POST" action="{{url_for('Profile.CreateUser')}}" style="width: 50%;margin-left : 25%;">
            <div class="row">
                <div class="col">
                    <input class="form-control input-lg" type="text" name="username" placeholder="User Name"
                        autofocus="">
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <input class="form-control input-lg" type="text" name="useremail" placeholder="User Email"
                        autofocus="">
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <input class="form-control input-lg" type="text" name="useraddress" placeholder="Avalanche Address"
                        autofocus="">
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <input class="form-control input-lg" type="password" name="password" placeholder="Password">
                </div>
            </div>
            <center><button class="btn btn-success font-weight-bold" type="submit">Register</button></center>
        </form>
    </div>
</div>
{% endblock %}